### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [koglesby/firstreposit#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by koglesby** [comment]
Alright, I believe I figured it out. I noticed that resizing the browser window on my PC didn't really work to preview the layout on mobile (before this addition). I had to actually upload it to heroku before I noticed the difference
Before adding the tag, if I resized the window on my PC, the page layout would respond as intended, but on the view on mobile wouldn't reflect that.

**Comment by BillyMassey** [comment]
Good Job! 👍
